spring:
  application:
    name: All4Runner
  datasource:
    url: jdbc:postgresql://localhost:5432/All4Runner
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:wjd747}
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always

jwt:
  keyId: ${keyId:topofthehead}
  accessTokenExpiration: ${accessTokenMinute:5}
  refreshTokenExpiration: ${refreshTokenMinute:720}